### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by aemcdonald** [nathanielmillard/Crate#26]
- [x] Create wireframe for new feature

**Comment by nathanielmillard** [comment]
[Miro Board with our wireframe](https://miro.com/app/board/o9J_lclZV_U=/)
<img width="526" alt="Screen Shot 2020-12-07 at 3 41 31 PM" src="https://user-images.githubusercontent.com/65516564/101414186-dbe4e280-38a2-11eb-8010-db7286f9ff7d.png">
